# Generated by Django 2.1.5 on 2019-01-06 20:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала загрузки')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала загрузки')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Ожидается'), ('finished', 'Завершена'), ('interrupted', 'Прервана')], max_length=16, verbose_name='Статус')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Сессия загрузки',
                'verbose_name_plural': 'Сессии загрузки',
            },
        ),
    ]
