# Generated by Django 2.2.2 on 2019-07-06 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0004_auto_20190516_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('previews', 'Предзаказы')], max_length=8, verbose_name='Тип')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала загрузки')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца загрузки')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Ожидается'), ('finished', 'Завершена'), ('interrupted', 'Прервана')], default='pending', max_length=16, verbose_name='Статус')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Сессия загрузки',
                'verbose_name_plural': 'Сессии загрузки',
            },
        ),
        migrations.CreateModel(
            name='ParsedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.ParseSession', verbose_name='Сессия загрузки')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult')),
            ],
            options={
                'verbose_name': 'Загруженный объект',
                'verbose_name_plural': 'Загруженные объекты',
            },
        ),
    ]
