# Generated by Django 2.1.5 on 2019-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsesession',
            name='type',
            field=models.CharField(blank=True, choices=[('previews', 'Предзаказы')], max_length=8, verbose_name='Тип'),
        ),
    ]
