# Generated by Django 2.2.2 on 2019-07-11 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsesession',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Дополнительные данные'),
        ),
    ]
