# Generated by Django 2.1.5 on 2019-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_parsesession_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsesession',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидается'), ('finished', 'Завершена'), ('interrupted', 'Прервана')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
