# Generated by Django 2.2.2 on 2019-08-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_parsesession_item_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32, unique=True, verbose_name='Имя хоста')),
            ],
            options={
                'verbose_name': 'Адрес сайта',
                'verbose_name_plural': 'Адреса сайтов',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('default_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.Site', verbose_name='Источник по умолчанию')),
            ],
            options={
                'verbose_name': 'Режим загрузки',
                'verbose_name_plural': 'Режимы загрузки',
            },
        ),
    ]
