# Generated by Django 2.1.5 on 2019-02-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0005_remove_taskresult_session'),
        ('parsers', '0003_auto_20190129_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.ParseSession', verbose_name='Сессия загрузки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult')),
            ],
            options={
                'verbose_name': 'Загруженный объект',
                'verbose_name_plural': 'Загруженные объекты',
            },
        ),
    ]
