# Generated by Django 2.1.5 on 2019-02-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_parsedobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedobject',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult'),
        ),
    ]
