# Generated by Django 2.1.5 on 2019-02-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20190202_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedobject',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.ParseSession', verbose_name='Сессия загрузки'),
        ),
    ]
