# Generated by Django 2.1.5 on 2019-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20190202_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsesession',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца загрузки'),
        ),
    ]
