# Generated by Django 2.1.5 on 2019-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin_title',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Код'),
        ),
    ]
