# Generated by Django 2.1.5 on 2019-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20190113_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.FloatField(blank=True, default=0, verbose_name='Закупочная цена')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('weight', models.FloatField(blank=True, default=100, verbose_name='Вес')),
                ('cover_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='ID обложки')),
                ('active', models.BooleanField(blank=True, default=False, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cover_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
