# Generated by Django 2.1.5 on 2019-01-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20190113_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Item', verbose_name='Товар'),
        ),
    ]
