# Generated by Django 2.1.5 on 2019-01-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20190113_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item', verbose_name='Товар'),
        ),
    ]
