# Generated by Django 2.1.5 on 2019-01-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20190113_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIdentifier',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Идентификатор товара',
                'verbose_name_plural': 'Идентификаторы товара',
            },
        ),
    ]
