# Generated by Django 2.1.5 on 2019-01-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_itemidentifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantIdentifier',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Variant', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Идентификатор вариации',
                'verbose_name_plural': 'Идентификаторы вариации',
            },
        ),
        migrations.RemoveField(
            model_name='itemidentifier',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemIdentifier',
        ),
    ]
