# Generated by Django 2.1.5 on 2019-01-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20190113_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=512, verbose_name='Название'),
        ),
    ]
