# Generated by Django 2.1.5 on 2019-01-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20190114_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='variant',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество в наличии'),
        ),
    ]
