# Generated by Django 2.1.5 on 2019-01-20 09:38

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20190120_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(commerce.models.Cover.dummy), to='commerce.Cover', verbose_name='Обложка'),
        ),
    ]
