# Generated by Django 2.1.5 on 2019-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_auto_20190120_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='midtown_code',
        ),
        migrations.AddField(
            model_name='publisher',
            name='midtown_cat_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Код категории Midtown'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='midtown_comp_cat_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Код категории сборников Midtown'),
        ),
    ]
