# Generated by Django 2.1.5 on 2019-01-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_auto_20190120_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='abbreviature',
            new_name='abbreviation',
        ),
    ]
