# Generated by Django 2.1.5 on 2019-01-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_auto_20190120_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='cover',
            new_name='_cover',
        ),
    ]
