# Generated by Django 2.1.5 on 2019-01-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_auto_20190121_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantidentifier',
            old_name='name',
            new_name='identifier',
        ),
    ]
