# Generated by Django 2.1.5 on 2019-01-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_auto_20190128_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='original_cover_url',
            new_name='original_url',
        ),
    ]
