# Generated by Django 2.1.5 on 2019-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_auto_20190129_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='default_monthly',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_weekly',
        ),
        migrations.AddField(
            model_name='publisher',
            name='default_mdtwn',
            field=models.BooleanField(blank=True, default=True, verbose_name='По умолчанию для Midtown Comics'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='default_prwld',
            field=models.BooleanField(blank=True, default=True, verbose_name='По умолчанию для Previews World'),
        ),
    ]
