# Generated by Django 2.1.5 on 2019-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_auto_20190129_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='default_mdtwn',
            new_name='default_midtown',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='default_prwld',
            new_name='default_previewsworld',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='category',
            name='midtown_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID категории на Midtown Comics'),
        ),
        migrations.AddField(
            model_name='category',
            name='midtown_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название категории на Midtown Comics'),
        ),
        migrations.AddField(
            model_name='category',
            name='previewsworld_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID категории на Previews World'),
        ),
        migrations.AddField(
            model_name='category',
            name='previewsworld_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название категории на Previews World'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='midtown_full_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Полное название на Midtown Comics'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='midtown_short_name',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Сокращение на Midtown Comics'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='previewsworld_full_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Полное название на Previews World'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='previewsworld_short_name',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Сокращение на Previews World'),
        ),
    ]
