# Generated by Django 2.1.5 on 2019-01-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_auto_20190129_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='previewsworld_cat_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Код категории Previews World'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='previewsworld_comp_cat_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Код категории сборников Previews World'),
        ),
    ]
