# Generated by Django 2.1.5 on 2019-02-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_auto_20190129_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='midtown_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='midtown_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='previewsworld_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='previewsworld_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_midtown',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_previewsworld',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='midtown_cat_code',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='midtown_comp_cat_code',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='midtown_full_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='midtown_short_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='previewsworld_cat_code',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='previewsworld_comp_cat_code',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='previewsworld_full_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='previewsworld_short_name',
        ),
    ]
