# Generated by Django 2.1.5 on 2019-02-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20190202_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='category',
        ),
    ]
