# Generated by Django 2.1.5 on 2019-02-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_remove_publisher_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='_cover',
            new_name='image',
        ),
    ]
