# Generated by Django 2.1.5 on 2019-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_cover_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='phash',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='pHash'),
        ),
    ]
