# Generated by Django 2.1.5 on 2019-02-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_auto_20190207_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=64, verbose_name='Адрес хранилища')),
                ('type', models.CharField(choices=[('image', 'Изображение')], max_length=8, verbose_name='Тип файлов')),
            ],
        ),
    ]
