# Generated by Django 2.1.5 on 2019-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.AddField(
            model_name='cover',
            name='format',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Тип файла'),
        ),
    ]
