# Generated by Django 2.1.5 on 2019-02-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_auto_20190211_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='hosted_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL на стороннем ресурсе'),
        ),
    ]
