# Generated by Django 2.1.5 on 2019-02-28 00:23

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_auto_20190211_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(commerce.models.Cover.dummy), to='commerce.Cover', verbose_name='Обложка'),
        ),
    ]
