# Generated by Django 2.2.2 on 2019-08-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0036_auto_20190706_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
