# Generated by Django 2.2.2 on 2019-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_auto_20190826_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(default='', max_length=32, verbose_name='Кратков название'),
        ),
    ]
