# Generated by Django 2.2.2 on 2019-08-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0038_category_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_name',
        ),
    ]
