# Generated by Django 2.2.2 on 2019-07-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0035_auto_20190228_0323'),
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32, unique=True, verbose_name='Имя хоста')),
            ],
            options={
                'verbose_name': 'Адрес сайта',
                'verbose_name_plural': 'Адреса сайтов',
            },
        ),
        migrations.CreateModel(
            name='PublisherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Сокращенное название')),
                ('singles_category_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код категории синглов')),
                ('tp_category_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код категории сборников')),
                ('default', models.BooleanField(blank=True, default=False, verbose_name='По умолчанию для этого сайта')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Publisher', verbose_name='Издатель')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previews.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Информация об издателе',
                'verbose_name_plural': 'Информация об издателях',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('monthly', 'Месяц'), ('weekly', 'Неделя')], max_length=8, null=True, verbose_name='Тип')),
                ('origin_url', models.URLField(blank=True, default='', verbose_name='Ссылка на оригинальный товар')),
                ('release_date', models.DateField(null=True, verbose_name='Дата выхода')),
                ('upc', models.CharField(max_length=20, null=True)),
                ('price_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.PriceMap', verbose_name='Таблица цен')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.ParseSession', verbose_name='Сессия загрузки')),
                ('variant', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Variant', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=16, null=True, verbose_name='ID категории')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название категории')),
                ('default', models.BooleanField(blank=True, default=False, verbose_name='По умолчанию для этого сайта')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Category', verbose_name='Категория')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previews.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Информация о категории',
                'verbose_name_plural': 'Информация о категориях',
            },
        ),
    ]
