# Generated by Django 2.1.5 on 2019-01-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsers', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('monthly', 'Месяц'), ('weekly', 'Неделя')], max_length=8, null=True, verbose_name='Тип')),
                ('origin_url', models.URLField(blank=True, default='', verbose_name='Ссылка на оригинальный товар')),
                ('title_origin', models.CharField(blank=True, default='Без названия', max_length=512, verbose_name='Оригинальное название')),
                ('diamond_id', models.CharField(max_length=9, null=True, verbose_name='ID Diamond')),
                ('release_date', models.DateField(null=True, verbose_name='Дата выхода')),
                ('midtown_id', models.CharField(max_length=64, null=True, verbose_name='Код Midtown')),
                ('cover_origin', models.URLField(blank=True, default='', null=True, verbose_name='Оригинальнаый адрес обложки')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Item', verbose_name='Товар')),
                ('price_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.PriceMap', verbose_name='Таблица цен')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.ParseSession', verbose_name='Сессия загрузки')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
    ]
