# Generated by Django 2.1.5 on 2019-01-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_variant_item'),
        ('previews', '0002_remove_preview_title_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='item',
        ),
        migrations.AddField(
            model_name='preview',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Variant', verbose_name='Товар'),
        ),
    ]
