# Generated by Django 2.1.5 on 2019-01-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0003_auto_20190113_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='variant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Variant', verbose_name='Товар'),
        ),
    ]
