# Generated by Django 2.1.5 on 2019-01-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0004_auto_20190120_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='cover_origin',
        ),
        migrations.AddField(
            model_name='preview',
            name='upc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preview',
            name='midtown_id',
            field=models.CharField(max_length=16, null=True, verbose_name='Код Midtown'),
        ),
    ]
