# Generated by Django 2.1.5 on 2019-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0005_auto_20190120_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='midtown_cat_id',
            field=models.PositiveIntegerField(max_length=4, null=True, verbose_name='Код категории Midtown'),
        ),
        migrations.AddField(
            model_name='preview',
            name='midtown_comp_cat_id',
            field=models.PositiveIntegerField(max_length=4, null=True, verbose_name='Код категории сборников Midtown'),
        ),
    ]
