# Generated by Django 2.1.5 on 2019-01-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0008_auto_20190120_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='diamond_id',
        ),
    ]
