# Generated by Django 2.1.5 on 2019-02-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20190202_0106'),
        ('previews', '0009_remove_preview_diamond_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=16, null=True, verbose_name='ID категории')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название категории')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Информация о категории',
                'verbose_name_plural': 'Информация о категориях',
            },
        ),
        migrations.CreateModel(
            name='PublisherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Сокращенное название')),
                ('singles_category_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код категории синглов')),
                ('tp_category_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код категории сборников')),
                ('default', models.BooleanField(blank=True, default=False, verbose_name='По умолчанию для этого сайта')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Информация об издателе',
                'verbose_name_plural': 'Информация об издателях',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32, unique=True, verbose_name='Имя хоста')),
            ],
            options={
                'verbose_name': 'Адрес сайта',
                'verbose_name_plural': 'Адреса сайтов',
            },
        ),
        migrations.AlterField(
            model_name='preview',
            name='variant',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Variant', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='publisherdata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previews.Site', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='categorydata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='previews.Site', verbose_name='Сайт'),
        ),
    ]
