# Generated by Django 2.1.5 on 2019-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0010_auto_20190202_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydata',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='По умолчанию для этого сайта'),
        ),
    ]
